/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import DBObject.Employee;
import DBObject.SQLTable;
import MainView.Home;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Phan Hau
 */
public class EmployeeController extends javax.swing.JFrame {
    private int TAG;
    private String ID;
    private int RowID;
    /**
     * Creates new form addEmployee
     */
    public EmployeeController() {
        TAG = 1;
        initComponents();
    }
    
    public EmployeeController(Object[] data, int RowID) {     
        TAG = 2;
        this.RowID = RowID;
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        initComponents();
        
        ID = (String) data[0];
        tf_ManagerID.setText((String) data[1]);
        tf_Fullname.setText((String) data[2]);
        tf_Address.setText((String) data[5]);
        tf_Account.setText((String) data[10]);
        tf_Position.setText((String) data[6]);
        tf_Salary.setText((String) data[8]);
        cbGender.setSelectedItem((String) data[3]);
        try {
            DC_Birth.setDate(format.parse((String) data[9]));
            DC_Start.setDate(format.parse((String) data[4]));
        } catch (ParseException ex) {
            Logger.getLogger(EmployeeController.class.getName()).log(Level.SEVERE, null, ex);
        }
        tf_Phone.setText((String) data[7]);
        tf_Password.setText((String) data[11]);
        
        DC_Start.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbCreateCustomerAccount1 = new javax.swing.JLabel();
        lbName1 = new javax.swing.JLabel();
        tf_ManagerID = new javax.swing.JTextField();
        lbName2 = new javax.swing.JLabel();
        tf_Fullname = new javax.swing.JTextField();
        lbName3 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        lbName4 = new javax.swing.JLabel();
        lbName5 = new javax.swing.JLabel();
        lbName6 = new javax.swing.JLabel();
        lbName7 = new javax.swing.JLabel();
        tf_Address = new javax.swing.JTextField();
        lbName8 = new javax.swing.JLabel();
        lbAccount = new javax.swing.JLabel();
        lbAccount1 = new javax.swing.JLabel();
        tf_Account = new javax.swing.JTextField();
        tf_Phone = new javax.swing.JTextField();
        tf_Position = new javax.swing.JTextField();
        tf_Salary = new javax.swing.JTextField();
        lbAccount2 = new javax.swing.JLabel();
        btnConfirm1 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        DC_Start = new com.toedter.calendar.JDateChooser();
        DC_Birth = new com.toedter.calendar.JDateChooser();
        tf_Password = new javax.swing.JTextField();

        lbName.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbName.setForeground(new java.awt.Color(120, 168, 252));
        lbName.setText("FOOD NAME:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbCreateCustomerAccount1.setBackground(new java.awt.Color(255, 255, 255));
        lbCreateCustomerAccount1.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        lbCreateCustomerAccount1.setForeground(new java.awt.Color(120, 168, 252));
        lbCreateCustomerAccount1.setText("EMPLOYEE INFO");

        lbName1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbName1.setForeground(new java.awt.Color(120, 168, 252));
        lbName1.setText("MANAGER ID:");

        tf_ManagerID.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_ManagerID.setForeground(new java.awt.Color(120, 168, 252));
        tf_ManagerID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_ManagerID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));

        lbName2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbName2.setForeground(new java.awt.Color(120, 168, 252));
        lbName2.setText("FULL NAME:");

        tf_Fullname.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_Fullname.setForeground(new java.awt.Color(120, 168, 252));
        tf_Fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Fullname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));

        lbName3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbName3.setForeground(new java.awt.Color(120, 168, 252));
        lbName3.setText("GENDER:");

        cbGender.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbGender.setForeground(new java.awt.Color(120, 168, 252));
        cbGender.setMaximumRowCount(2);
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cbGender.setBorder(null);

        lbName4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbName4.setForeground(new java.awt.Color(120, 168, 252));
        lbName4.setText("ADDRESS:");

        lbName5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbName5.setForeground(new java.awt.Color(120, 168, 252));
        lbName5.setText("SALARY: ");

        lbName6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbName6.setForeground(new java.awt.Color(120, 168, 252));
        lbName6.setText("PHONE:");

        lbName7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbName7.setForeground(new java.awt.Color(120, 168, 252));
        lbName7.setText("BIRTHDAY:");

        tf_Address.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_Address.setForeground(new java.awt.Color(120, 168, 252));
        tf_Address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));

        lbName8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbName8.setForeground(new java.awt.Color(120, 168, 252));
        lbName8.setText("POSITION: ");

        lbAccount.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbAccount.setForeground(new java.awt.Color(120, 168, 252));
        lbAccount.setText("ACCOUNT:");

        lbAccount1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbAccount1.setForeground(new java.awt.Color(120, 168, 252));
        lbAccount1.setText("PASSWORD:");

        tf_Account.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_Account.setForeground(new java.awt.Color(120, 168, 252));
        tf_Account.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Account.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));

        tf_Phone.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_Phone.setForeground(new java.awt.Color(120, 168, 252));
        tf_Phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Phone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));

        tf_Position.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_Position.setForeground(new java.awt.Color(120, 168, 252));
        tf_Position.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Position.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));

        tf_Salary.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_Salary.setForeground(new java.awt.Color(120, 168, 252));
        tf_Salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Salary.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));

        lbAccount2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbAccount2.setForeground(new java.awt.Color(120, 168, 252));
        lbAccount2.setText("DATE START:");

        btnConfirm1.setBackground(new java.awt.Color(120, 168, 252));
        btnConfirm1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnConfirm1.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm1.setText("CONFIRM");
        btnConfirm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirm1MouseClicked(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(129, 0, 0));
        btnExit.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("CANCEL");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        DC_Start.setDateFormatString("dd/MM/yyyy");

        tf_Password.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_Password.setForeground(new java.awt.Color(120, 168, 252));
        tf_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbName1)
                            .addComponent(lbName2)
                            .addComponent(lbName8)
                            .addComponent(lbAccount)
                            .addComponent(lbName4)
                            .addComponent(lbName5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_ManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbName3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbAccount2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbAccount1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbName6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(lbName7))
                            .addComponent(tf_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btnConfirm1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(btnExit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(tf_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DC_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DC_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(lbCreateCustomerAccount1)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbCreateCustomerAccount1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ManagerID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbName3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbName2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbName7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(DC_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Account, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbName8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbAccount2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DC_Start, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnConfirm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirm1MouseClicked
        if (TAG == 1) {
            add(evt);
        } 
        else if (TAG == 2) {
            update(evt);
        }
    }//GEN-LAST:event_btnConfirm1MouseClicked
    
    private void update(java.awt.event.MouseEvent evt) {
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        
        String ManagerID = tf_ManagerID.getText();
        String FullName = tf_Fullname.getText();
        String Address = tf_Address.getText();
        String Account = tf_Account.getText();
        String Position = tf_Position.getText();
        int Salary = Integer.parseInt(tf_Salary.getText());
        String Gender = (String) cbGender.getSelectedItem();
        String Birth = format.format(DC_Birth.getDate());
        String Phone = tf_Phone.getText();
        String Password = tf_Password.getText();
        String query = "update NHANVIEN "
                        + "set MAQUANLY = ?, HOTEN = ?, GIOITINH = ?, DIACHI = ?, CHUCVU = ?, SDT = ?, LUONG = ?, NGSINH = ?, TAIKHOAN = ?, MATKHAU = ?"
                        + "where MANV = ?";
        try {
            PreparedStatement p_statement = SQLTable.connection.prepareStatement(query);
            p_statement.setString(1, ManagerID);
            p_statement.setString(2, FullName);
            p_statement.setString(3, Gender);
            p_statement.setString(4, Address);
            p_statement.setString(5, Position);
            p_statement.setString(6, Phone);
            p_statement.setInt(7, Salary);
            p_statement.setDate(8, new java.sql.Date(DC_Birth.getDate().getTime()));
            p_statement.setString(9, Account);
            p_statement.setString(10, Password);
            p_statement.setString(11, ID);

            p_statement.executeUpdate();
            System.out.println("SUCCESS");

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        finally {
            Object[] data = (new Employee(ID, ManagerID, FullName, Gender, format.format(DC_Start.getDate()), Address, Position, Phone, Salary, Birth, Account, Password)).get_Properties();
            Home.update(data, RowID);
            DC_Start.enable(true);
            dispose();
        } 
        
                
    }
    
    private void add(java.awt.event.MouseEvent evt) {
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String ManagerID = tf_ManagerID.getText();
        String FullName = tf_Fullname.getText();
        String Address = tf_Address.getText();
        String Account = tf_Account.getText();
        String Position = tf_Position.getText();
        int Salary = Integer.parseInt(tf_Salary.getText());
        String Gender = (String) cbGender.getSelectedItem();
        String Birth = format.format(DC_Birth.getDate());
        String Start = format.format(DC_Start.getDate());
        String Phone = tf_Phone.getText();
        String Password = tf_Password.getText();
        String ID = Home.getTableID();

        String query = "insert into NHANVIEN values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            PreparedStatement p_statement = SQLTable.connection.prepareStatement(query);
            p_statement.setString(1, ID);
            p_statement.setString(2, ManagerID);
            p_statement.setString(3, FullName);
            p_statement.setString(4, Gender);
            p_statement.setDate(5, new java.sql.Date(DC_Start.getDate().getTime()));
            p_statement.setString(6, Address);
            p_statement.setString(7, Position);
            p_statement.setString(8, Phone);
            p_statement.setInt(9, Salary);
            p_statement.setDate(10, new java.sql.Date(DC_Birth.getDate().getTime()));
            p_statement.setString(11, Account);
            p_statement.setString(12, Password);

            p_statement.executeUpdate();
            System.out.println("INSERT SUCCESS");
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        finally {
            Object[] data = (new Employee(ID, ManagerID, FullName, Gender, format.format(DC_Start.getDate()), Address, Position, Phone, Salary, Birth, Account, Password)).get_Properties();
            Home.update(data);
            dispose();
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeController().setVisible(true);
                new EmployeeController().setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DC_Birth;
    private com.toedter.calendar.JDateChooser DC_Start;
    private javax.swing.JButton btnConfirm1;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JLabel lbAccount1;
    private javax.swing.JLabel lbAccount2;
    private javax.swing.JLabel lbCreateCustomerAccount1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbName1;
    private javax.swing.JLabel lbName2;
    private javax.swing.JLabel lbName3;
    private javax.swing.JLabel lbName4;
    private javax.swing.JLabel lbName5;
    private javax.swing.JLabel lbName6;
    private javax.swing.JLabel lbName7;
    private javax.swing.JLabel lbName8;
    private javax.swing.JTextField tf_Account;
    private javax.swing.JTextField tf_Address;
    private javax.swing.JTextField tf_Fullname;
    private javax.swing.JTextField tf_ManagerID;
    private javax.swing.JTextField tf_Password;
    private javax.swing.JTextField tf_Phone;
    private javax.swing.JTextField tf_Position;
    private javax.swing.JTextField tf_Salary;
    // End of variables declaration//GEN-END:variables
}
