/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import DBObject.Employee;
import DBObject.SQLTable;
import DBObject.Ticket;
import MainView.Home;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author DangT
 */
public class TicketController extends javax.swing.JFrame {
    private int TAG;
    private String ID;
    private int RowID;
    private Date date;
    /**
     * Creates new form TicketController
     */
    public TicketController() {
        date = new Date();
        initComponents();
    }
    
    public TicketController(Object[] data, int RowID) {     
        TAG = 2;
        date = new Date();
        this.RowID = RowID;
        initComponents();
        
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        ID = (String) data[0];
        tf_MABAN.setText((String) data[1]);
        tf_MAKH.setText((String) data[2]);
        try {         
            DC_BOOK.setDate(format.parse((String) data[3]));
            DC_CREATE.setDate(format.parse((String) data[4]));
        } catch (ParseException ex) {
            Logger.getLogger(TicketController.class.getName()).log(Level.SEVERE, null, ex);
        }
        format = new SimpleDateFormat("HH:mm:ss");
        tf_TONGCB.setText((String) data[5]);
        tf_TONGMK.setText((String) data[6]);
        try {
            Spin_BEGIN.setValue(format.parse((String) data[7]));
            Spin_END.setValue(format.parse((String) data[8]));
        } catch (ParseException ex) {
            Logger.getLogger(TicketController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lb_Title = new javax.swing.JLabel();
        lb_MAKH = new javax.swing.JLabel();
        tf_MAKH = new javax.swing.JTextField();
        lb_MABAN = new javax.swing.JLabel();
        tf_MABAN = new javax.swing.JTextField();
        lb_BOOK = new javax.swing.JLabel();
        lb_CREATE = new javax.swing.JLabel();
        lb_BEGIN = new javax.swing.JLabel();
        lb_TONGCB = new javax.swing.JLabel();
        lb_TONGMK = new javax.swing.JLabel();
        tf_TONGCB = new javax.swing.JTextField();
        lb_END = new javax.swing.JLabel();
        btnConfirm4 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        DC_BOOK = new com.toedter.calendar.JDateChooser();
        DC_CREATE = new com.toedter.calendar.JDateChooser();
        tf_TONGMK = new javax.swing.JTextField();
        SpinnerDateModel sm2 =
        new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        Spin_END = new javax.swing.JSpinner(sm2);
        SpinnerDateModel sm1 = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        Spin_BEGIN = new javax.swing.JSpinner(sm1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1040, 500));

        lb_Title.setText("TICKET INFO");
        lb_Title.setBackground(new java.awt.Color(255, 255, 255));
        lb_Title.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        lb_Title.setForeground(new java.awt.Color(120, 168, 252));

        lb_MAKH.setText("CUSTOMER ID:");
        lb_MAKH.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lb_MAKH.setForeground(new java.awt.Color(120, 168, 252));

        tf_MAKH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_MAKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));
        tf_MAKH.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_MAKH.setForeground(new java.awt.Color(120, 168, 252));

        lb_MABAN.setText("TABLE ID:");
        lb_MABAN.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lb_MABAN.setForeground(new java.awt.Color(120, 168, 252));

        tf_MABAN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_MABAN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));
        tf_MABAN.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_MABAN.setForeground(new java.awt.Color(120, 168, 252));

        lb_BOOK.setText("BOOK DATE:");
        lb_BOOK.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lb_BOOK.setForeground(new java.awt.Color(120, 168, 252));

        lb_CREATE.setText("CREATE DATE:");
        lb_CREATE.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lb_CREATE.setForeground(new java.awt.Color(120, 168, 252));

        lb_BEGIN.setText("BEGIN AT:");
        lb_BEGIN.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lb_BEGIN.setForeground(new java.awt.Color(120, 168, 252));

        lb_TONGCB.setText("COMBO MONEY:");
        lb_TONGCB.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lb_TONGCB.setForeground(new java.awt.Color(120, 168, 252));

        lb_TONGMK.setText("FOOD MONEY:");
        lb_TONGMK.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lb_TONGMK.setForeground(new java.awt.Color(120, 168, 252));

        tf_TONGCB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TONGCB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));
        tf_TONGCB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_TONGCB.setForeground(new java.awt.Color(120, 168, 252));
        tf_TONGCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TONGCBActionPerformed(evt);
            }
        });

        lb_END.setText("END AT:");
        lb_END.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lb_END.setForeground(new java.awt.Color(120, 168, 252));

        btnConfirm4.setText("CONFIRM");
        btnConfirm4.setBackground(new java.awt.Color(120, 168, 252));
        btnConfirm4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnConfirm4.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirm4MouseClicked(evt);
            }
        });

        btnExit.setText("CANCEL");
        btnExit.setBackground(new java.awt.Color(129, 0, 0));
        btnExit.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        DC_BOOK.setDateFormatString("dd/MM/yyyy");

        DC_CREATE.setDateFormatString("dd/MM/yyyy");

        tf_TONGMK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TONGMK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(120, 168, 252)));
        tf_TONGMK.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tf_TONGMK.setForeground(new java.awt.Color(120, 168, 252));

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(Spin_END, "HH:mm:ss");
        Spin_END.setEditor(de2);

        JSpinner.DateEditor de1 = new JSpinner.DateEditor(Spin_BEGIN, "HH:mm:ss");
        Spin_BEGIN.setEditor(de1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_TONGCB)
                    .addComponent(lb_MAKH)
                    .addComponent(lb_MABAN)
                    .addComponent(lb_BEGIN))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(tf_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_BOOK))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tf_MABAN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(lb_CREATE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_TONGCB, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(Spin_BEGIN))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_TONGMK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_END, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnConfirm4)
                        .addGap(46, 46, 46)
                        .addComponent(btnExit)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DC_CREATE, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(DC_BOOK, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(tf_TONGMK)
                            .addComponent(Spin_END))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(lb_Title)
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Title)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_BOOK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_MABAN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_MABAN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_CREATE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(DC_BOOK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DC_CREATE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_TONGCB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_TONGCB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_TONGMK, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_TONGMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_BEGIN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_END, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spin_END, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spin_BEGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirm4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirm4MouseClicked
        if (TAG == 1) {
            add(evt);
        } 
        else if (TAG == 2) {
            update(evt);
        }
    }//GEN-LAST:event_btnConfirm4MouseClicked
    
    private void update(java.awt.event.MouseEvent evt) {
        DateFormat dformat = new SimpleDateFormat("dd/MM/yyyy");
        DateFormat tformat = new SimpleDateFormat("HH:mm:ss");
        
        String tableID = tf_MABAN.getText();
        String cusID = tf_MAKH.getText();
        Date BookDate = DC_BOOK.getDate();
        Date CreateDate = DC_CREATE.getDate();
        int TongCB = Integer.parseInt(tf_TONGCB.getText());
        int TongMK = Integer.parseInt(tf_TONGMK.getText());
        String Begin = tformat.format((Date) Spin_BEGIN.getValue());
        String End =  tformat.format((Date) Spin_END.getValue());
        String query = "update VE "
                        + "set MABAN = ?, MAKH = ?, NGAN = ?, NGDV = ?, TONGCB = ?, TONGMK = ?, TGBD = ?, TGKT = ?"
                        + "where MAVE = ?";
        try {
            PreparedStatement p_statement = SQLTable.connection.prepareStatement(query);
            p_statement.setString(1, tableID);
            p_statement.setString(2, cusID);
            p_statement.setDate(3, new java.sql.Date(BookDate.getTime()));
            p_statement.setDate(4, new java.sql.Date(CreateDate.getTime()));
            p_statement.setString(5, tf_TONGCB.getText());
            p_statement.setString(6, tf_TONGMK.getText());
            p_statement.setDate(7, new java.sql.Date(((Date) Spin_BEGIN.getValue()).getTime()));
            p_statement.setDate(8, new java.sql.Date(((Date) Spin_END.getValue()).getTime()));
            p_statement.setString(9, ID);

            p_statement.executeUpdate();
            Object[] data = (new Ticket(ID, tableID, cusID, dformat.format(BookDate), dformat.format(CreateDate), TongCB, TongMK, Begin, End)).get_Properties();
            Home.update(data, RowID);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        finally {        
            dispose();
        } 
        
                
    }
    
    private void add(java.awt.event.MouseEvent evt) {
        DateFormat dformat = new SimpleDateFormat("dd/MM/yyyy");
        DateFormat tformat = new SimpleDateFormat("HH:mm:ss");
        
        String tableID = tf_MABAN.getText();
        String cusID = tf_MAKH.getText();
        Date BookDate = DC_BOOK.getDate();
        Date CreateDate = DC_CREATE.getDate();
        int TongCB = Integer.parseInt(tf_TONGCB.getText());
        int TongMK = Integer.parseInt(tf_TONGMK.getText());
        Date Begin = (Date) Spin_BEGIN.getValue();
        Date End =  (Date) Spin_END.getValue();
        String ID = Home.getTableID();
  

        String query = "insert into VE values (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            PreparedStatement p_statement = SQLTable.connection.prepareStatement(query);
            p_statement.setString(1, ID);
            p_statement.setString(2, tableID);
            p_statement.setString(3, cusID);
            p_statement.setDate(4, new java.sql.Date(BookDate.getTime()));
            p_statement.setDate(5, new java.sql.Date(CreateDate.getTime()));
            p_statement.setInt(6, TongCB);
            p_statement.setInt(7, TongMK);
            p_statement.setDate(8, new java.sql.Date(Begin.getTime()));
            p_statement.setDate(9, new java.sql.Date(End.getTime()));
                
            p_statement.executeUpdate();
            Object[] data = (new Ticket(ID, tableID, cusID, dformat.format(BookDate), dformat.format(CreateDate), TongCB, TongMK, tformat.format(Begin), tformat.format(End))).get_Properties();  
            Home.update(data, RowID);           
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        finally {
            dispose();
        } 
    }
    
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void tf_TONGCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TONGCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TONGCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DC_BOOK;
    private com.toedter.calendar.JDateChooser DC_CREATE;
    private javax.swing.JSpinner Spin_BEGIN;
    private javax.swing.JSpinner Spin_END;
    private javax.swing.JButton btnConfirm4;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lb_BEGIN;
    private javax.swing.JLabel lb_BOOK;
    private javax.swing.JLabel lb_CREATE;
    private javax.swing.JLabel lb_END;
    private javax.swing.JLabel lb_MABAN;
    private javax.swing.JLabel lb_MAKH;
    private javax.swing.JLabel lb_TONGCB;
    private javax.swing.JLabel lb_TONGMK;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JTextField tf_MABAN;
    private javax.swing.JTextField tf_MAKH;
    private javax.swing.JTextField tf_TONGCB;
    private javax.swing.JTextField tf_TONGMK;
    // End of variables declaration//GEN-END:variables
}
