/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.KhachHangController;
import DBObject.SQLTable;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author DangT
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        lb_Error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Title = new javax.swing.JLabel();
        lb_Error = new javax.swing.JLabel();
        lb_UserName = new javax.swing.JLabel();
        lb_Password = new javax.swing.JLabel();
        lb_RetypePassword = new javax.swing.JLabel();
        lb_FullName = new javax.swing.JLabel();
        lb_Gender = new javax.swing.JLabel();
        lb_Phone = new javax.swing.JLabel();
        lb_Address = new javax.swing.JLabel();
        lb_Brithday = new javax.swing.JLabel();
        lb_InviteCode = new javax.swing.JLabel();
        btn_Confirm = new javax.swing.JButton();
        tf_UserName = new javax.swing.JTextField();
        tf_FullName = new javax.swing.JTextField();
        tf_Phone = new javax.swing.JTextField();
        tf_Address = new javax.swing.JTextField();
        tf_InviteCode = new javax.swing.JTextField();
        dc_Birthday = new com.toedter.calendar.JDateChooser();
        cb_Gender = new javax.swing.JComboBox<>();
        tf_RetypePassword = new javax.swing.JPasswordField();
        tf_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lb_Title.setBackground(new java.awt.Color(255, 255, 255));
        lb_Title.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lb_Title.setForeground(new java.awt.Color(120, 168, 252));
        lb_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Title.setText("REGISTER");
        lb_Title.setToolTipText("");

        lb_Error.setForeground(new java.awt.Color(255, 51, 51));
        lb_Error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Error.setText("Your information is incorrect");

        lb_UserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_UserName.setForeground(new java.awt.Color(120, 168, 252));
        lb_UserName.setText("Username");

        lb_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Password.setForeground(new java.awt.Color(120, 168, 252));
        lb_Password.setText("Password");

        lb_RetypePassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_RetypePassword.setForeground(new java.awt.Color(120, 168, 252));
        lb_RetypePassword.setText("Retype Password");

        lb_FullName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_FullName.setForeground(new java.awt.Color(120, 168, 252));
        lb_FullName.setText("Full Name");

        lb_Gender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Gender.setForeground(new java.awt.Color(120, 168, 252));
        lb_Gender.setText("Gender");

        lb_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Phone.setForeground(new java.awt.Color(120, 168, 252));
        lb_Phone.setText("Phone");

        lb_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Address.setForeground(new java.awt.Color(120, 168, 252));
        lb_Address.setText("Address");

        lb_Brithday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Brithday.setForeground(new java.awt.Color(120, 168, 252));
        lb_Brithday.setText("Birthday");

        lb_InviteCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_InviteCode.setForeground(new java.awt.Color(120, 168, 252));
        lb_InviteCode.setText("Invite Code");

        btn_Confirm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Confirm.setText("Confirm");
        btn_Confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ConfirmMouseClicked(evt);
            }
        });

        tf_UserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf_FullName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf_InviteCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dc_Birthday.setDateFormatString("dd/MM/yyyy");

        cb_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lb_Title))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_UserName)
                        .addGap(74, 74, 74)
                        .addComponent(tf_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_Password)
                        .addGap(78, 78, 78)
                        .addComponent(tf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lb_RetypePassword)
                        .addGap(18, 18, 18)
                        .addComponent(tf_RetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lb_FullName)
                        .addGap(74, 74, 74)
                        .addComponent(tf_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lb_Gender)
                        .addGap(96, 96, 96)
                        .addComponent(cb_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lb_Phone)
                        .addGap(103, 103, 103)
                        .addComponent(tf_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lb_Address)
                        .addGap(90, 90, 90)
                        .addComponent(tf_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lb_Brithday)
                        .addGap(87, 87, 87)
                        .addComponent(dc_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lb_InviteCode)
                        .addGap(61, 61, 61)
                        .addComponent(tf_InviteCode, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lb_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btn_Confirm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lb_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lb_UserName))
                    .addComponent(tf_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lb_Password))
                    .addComponent(tf_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_RetypePassword)
                    .addComponent(tf_RetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lb_FullName))
                    .addComponent(tf_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lb_Gender))
                    .addComponent(cb_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lb_Phone))
                    .addComponent(tf_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lb_Address))
                    .addComponent(tf_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Brithday)
                    .addComponent(dc_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lb_InviteCode))
                    .addComponent(tf_InviteCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_Error)
                .addGap(18, 18, 18)
                .addComponent(btn_Confirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfirmMouseClicked
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        
        if (isOK()) {
            String FullName = tf_FullName.getText();
            String Gender = (String) cb_Gender.getSelectedItem();
            String Type = "0";
            String Phone = tf_Phone.getText();
            String Address = tf_Address.getText();
            String Birth = format.format(dc_Birthday.getDate());
            String Reg = format.format(new Date());
            String Account  = tf_UserName.getText();
            String Password = tf_RetypePassword.getText();
            String InviteCode = tf_InviteCode.getText();
            String Point = "0";
            String ID = SQLTable.getTableID("KHACHHANG", "KH");
            
            Object[] data = {ID, FullName, Gender, Birth, Type, Phone, Address, Reg, Account, Password, InviteCode, Point};
            KhachHangController.add(data);
            LoginForm form = new LoginForm();
            form.setVisible(true);
            dispose();   
        }
        else {
            lb_Error.setVisible(true);
            setBorder();
        }
    }//GEN-LAST:event_btn_ConfirmMouseClicked
    
    private void setBorder() {
        Border errorBorder = BorderFactory.createLineBorder(Color.RED, 1);
        tf_UserName.setBorder(errorBorder);
        tf_RetypePassword.setBorder(errorBorder);
        tf_Password.setBorder(errorBorder);
        tf_Phone.setBorder(errorBorder);
        tf_Address.setBorder(errorBorder);
        tf_FullName.setBorder(errorBorder);
        dc_Birthday.setBorder(errorBorder); 
    }
    
    private boolean isOK() {
        return !isEmpty() && isMatch();
    }
    
    private boolean isEmpty() {
        return tf_UserName.getText().isEmpty() && tf_RetypePassword.getText().isEmpty() 
            && tf_Password.getText().isEmpty() && tf_FullName.getText().isEmpty()
            && tf_Phone.getText().isEmpty() && tf_Address.getText().isEmpty()
            && (dc_Birthday.getDate() == null);
    }
    
    
    private boolean isMatch() {
        return tf_RetypePassword.getText().equals(tf_Password.getText());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Confirm;
    private javax.swing.JComboBox<String> cb_Gender;
    private com.toedter.calendar.JDateChooser dc_Birthday;
    private javax.swing.JLabel lb_Address;
    private javax.swing.JLabel lb_Brithday;
    private javax.swing.JLabel lb_Error;
    private javax.swing.JLabel lb_FullName;
    private javax.swing.JLabel lb_Gender;
    private javax.swing.JLabel lb_InviteCode;
    private javax.swing.JLabel lb_Password;
    private javax.swing.JLabel lb_Phone;
    private javax.swing.JLabel lb_RetypePassword;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JLabel lb_UserName;
    private javax.swing.JTextField tf_Address;
    private javax.swing.JTextField tf_FullName;
    private javax.swing.JTextField tf_InviteCode;
    private javax.swing.JPasswordField tf_Password;
    private javax.swing.JTextField tf_Phone;
    private javax.swing.JPasswordField tf_RetypePassword;
    private javax.swing.JTextField tf_UserName;
    // End of variables declaration//GEN-END:variables
}
