/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DBObject.SQLTable;
import MainView.CustomerHome;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author DangT
 */
public class TaiKhoan extends javax.swing.JFrame {

    public static Object[] data = null;
    CustomerHome home;
    public TaiKhoan() {
        initComponents();
        initInfo();
        home = new CustomerHome();
        lb_Error.setVisible(false);
    }
    
    public void AccountInformation(Object[] data) {
        initComponents();
        this.data = data;
        initInfo();
    }
    
    private void initInfo() {
        if (data != null) {
            DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            tf_FullName.setText((String) data[0]);
            cb_Gender.setSelectedItem((String) data[1]);
            try {
                dc_Birthday.setDate(format.parse((String) data[2]));
            } catch (ParseException ex) {
                Logger.getLogger(TaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            }
            tf_Address.setText((String) data[3]);
            tf_Phone.setText((String) data[4]);
            tf_InviteCode.setText((String) data[5]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Title = new javax.swing.JLabel();
        lb_FullName = new javax.swing.JLabel();
        lb_Gender = new javax.swing.JLabel();
        lb_Birthday = new javax.swing.JLabel();
        lb_Address = new javax.swing.JLabel();
        lb_Phone = new javax.swing.JLabel();
        lb_InviteCode = new javax.swing.JLabel();
        btn_Confirm = new javax.swing.JButton();
        tf_FullName = new javax.swing.JTextField();
        tf_Address = new javax.swing.JTextField();
        tf_Phone = new javax.swing.JTextField();
        tf_InviteCode = new javax.swing.JTextField();
        cb_Gender = new javax.swing.JComboBox<>();
        dc_Birthday = new com.toedter.calendar.JDateChooser();
        lb_Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ACCOUNT INFORMATION");

        lb_Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_Title.setForeground(new java.awt.Color(120, 168, 252));
        lb_Title.setText("Account Information");

        lb_FullName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_FullName.setForeground(new java.awt.Color(120, 168, 252));
        lb_FullName.setText("Full Name");

        lb_Gender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Gender.setForeground(new java.awt.Color(120, 168, 252));
        lb_Gender.setText("Gender");

        lb_Birthday.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Birthday.setForeground(new java.awt.Color(120, 168, 252));
        lb_Birthday.setText("BirthDay");

        lb_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Address.setForeground(new java.awt.Color(120, 168, 252));
        lb_Address.setText("Address");

        lb_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_Phone.setForeground(new java.awt.Color(120, 168, 252));
        lb_Phone.setText("Phone");

        lb_InviteCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_InviteCode.setForeground(new java.awt.Color(120, 168, 252));
        lb_InviteCode.setText("Invite code");

        btn_Confirm.setText("Confirm");
        btn_Confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ConfirmMouseClicked(evt);
            }
        });

        tf_FullName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_FullNameActionPerformed(evt);
            }
        });

        tf_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf_InviteCode.setEditable(false);
        tf_InviteCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cb_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        dc_Birthday.setDateFormatString("dd/MM/yyyy");

        lb_Error.setForeground(new java.awt.Color(255, 51, 51));
        lb_Error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Error.setText("Your information is incorrect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lb_Title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btn_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_FullName)
                                    .addComponent(lb_Phone)
                                    .addComponent(lb_InviteCode)
                                    .addComponent(lb_Address)
                                    .addComponent(lb_Birthday)
                                    .addComponent(lb_Gender))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_Phone)
                                    .addComponent(tf_Address)
                                    .addComponent(tf_FullName)
                                    .addComponent(tf_InviteCode)
                                    .addComponent(cb_Gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dc_Birthday, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_FullName)
                    .addComponent(tf_FullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Gender)
                    .addComponent(cb_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Birthday)
                    .addComponent(dc_Birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Address)
                    .addComponent(tf_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Phone)
                    .addComponent(tf_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_InviteCode)
                    .addComponent(tf_InviteCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_Error)
                .addGap(17, 17, 17)
                .addComponent(btn_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_FullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_FullNameActionPerformed

    private void btn_ConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfirmMouseClicked
        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String HoTen = tf_FullName.getText();
        String GT = (String) cb_Gender.getSelectedItem();
        String SN = format.format(dc_Birthday.getDate());
        String DiaChi = tf_Address.getText();
        String SDT = tf_Phone.getText();
          
        String query = "UPDATE KHACHHANG "
                + "SET HOTEN = ?, GIOITINH = ?, NGSINH = ?, DIACHI = ?, SDT = ?"
                + "WHERE MAKH = ?";
        
        try {
            PreparedStatement stm = SQLTable.connection.prepareStatement(query);
            stm.setString(1, HoTen);
            stm.setString(2, GT);
            stm.setDate(3, new java.sql.Date(dc_Birthday.getDate().getTime()));
            stm.setString(4, DiaChi);
            stm.setString(5, SDT);
            stm.setString(6, CustomerHome.MaKH);
            
            stm.execute();
            JOptionPane.showMessageDialog(null, "Update success");
            data = new Object[] {HoTen, GT, SN, DiaChi, SDT, data[5]};
            dispose();
        }
        catch (Exception ex) {
            System.out.println(ex.getMessage());
            lb_Error.setVisible(true);
            setBorder();
        }
    }//GEN-LAST:event_btn_ConfirmMouseClicked
    
    private void setBorder() {
        Border errorBorder = BorderFactory.createLineBorder(Color.RED, 1);
        tf_FullName.setBorder(errorBorder);
        tf_Address.setBorder(errorBorder);
        tf_Phone.setBorder(errorBorder);
        dc_Birthday.setBorder(errorBorder);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Confirm;
    private javax.swing.JComboBox<String> cb_Gender;
    private com.toedter.calendar.JDateChooser dc_Birthday;
    private javax.swing.JLabel lb_Address;
    private javax.swing.JLabel lb_Birthday;
    private javax.swing.JLabel lb_Error;
    private javax.swing.JLabel lb_FullName;
    private javax.swing.JLabel lb_Gender;
    private javax.swing.JLabel lb_InviteCode;
    private javax.swing.JLabel lb_Phone;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JTextField tf_Address;
    private javax.swing.JTextField tf_FullName;
    private javax.swing.JTextField tf_InviteCode;
    private javax.swing.JTextField tf_Phone;
    // End of variables declaration//GEN-END:variables
}
