/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginView;

/**
 *
 * @author Phan Hau
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_LoginForm = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Label_Login = new javax.swing.JLabel();
        TextField_UserName = new javax.swing.JTextField();
        Label_UserName = new javax.swing.JLabel();
        Label_Password = new javax.swing.JLabel();
        TextField_Password = new javax.swing.JPasswordField();
        Button_Login = new javax.swing.JButton();
        Label_Register = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Panel_LoginForm.setBackground(new java.awt.Color(255, 255, 255));
        Panel_LoginForm.setMinimumSize(new java.awt.Dimension(785, 578));
        Panel_LoginForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(120, 168, 252));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BuffetGO");
        jLabel3.setAlignmentX(0.5F);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(458, Short.MAX_VALUE))
        );

        Panel_LoginForm.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 578));

        Label_Login.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        Label_Login.setForeground(new java.awt.Color(102, 102, 102));
        Label_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Login.setText("Login");
        Panel_LoginForm.add(Label_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 115, 68));

        TextField_UserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        TextField_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_UserNameActionPerformed(evt);
            }
        });
        Panel_LoginForm.add(TextField_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 205, 309, 41));

        Label_UserName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Label_UserName.setForeground(new java.awt.Color(102, 102, 102));
        Label_UserName.setText("User name");
        Panel_LoginForm.add(Label_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 176, 99, -1));

        Label_Password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Label_Password.setForeground(new java.awt.Color(102, 102, 102));
        Label_Password.setText("Password");
        Panel_LoginForm.add(Label_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 296, 99, -1));

        TextField_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TextField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_PasswordActionPerformed(evt);
            }
        });
        Panel_LoginForm.add(TextField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 325, 309, 42));

        Button_Login.setBackground(new java.awt.Color(120, 168, 252));
        Button_Login.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Button_Login.setForeground(new java.awt.Color(240, 240, 240));
        Button_Login.setText("Sign In");
        Button_Login.setBorder(null);
        Button_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_LoginForm.add(Button_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 86, 40));

        Label_Register.setForeground(new java.awt.Color(120, 168, 252));
        Label_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Register.setText("Don't have an account?");
        Panel_LoginForm.add(Label_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 242, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_LoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_UserNameActionPerformed

    private void TextField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Login;
    private javax.swing.JLabel Label_Login;
    private javax.swing.JLabel Label_Password;
    private javax.swing.JLabel Label_Register;
    private javax.swing.JLabel Label_UserName;
    private javax.swing.JPanel Panel_LoginForm;
    private javax.swing.JPasswordField TextField_Password;
    private javax.swing.JTextField TextField_UserName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
